sudo: false
language: python
install:
    - pip install tox-travis
script:
    - tox

# List all environments configured in tox.ini to test them all using
# Travis CI!
env:
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
